// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"learning_go/webook/article/ioc"
	article2 "learning_go/webook/article/repository/article"
	"learning_go/webook/article/repository/cache"
	"learning_go/webook/article/repository/dao/article"
	"learning_go/webook/article/service"
)

// Injectors from wire.go:

func InitApp() *App {
	db := ioc.InitDB()
	articleDao := article.NewGormArticleDao(db)
	cmdable := ioc.InitRedis()
	articleCache := cache.NewRedisArticleCache(cmdable)
	articleRepository := article2.NewCachedArticleRepository(articleDao, articleCache)
	articleService := service.NewArticleServiceI(articleRepository)
	server := ioc.InitGRPCXServer(articleService)
	app := &App{
		server: server,
	}
	return app
}

// wire.go:

var (
	thirdProvider = wire.NewSet(ioc.InitDB, ioc.InitRedis)
)
