// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"learning_go/webook/interactive/grpc"
	"learning_go/webook/interactive/ioc"
	"learning_go/webook/interactive/repository"
	"learning_go/webook/interactive/repository/cache"
	"learning_go/webook/interactive/repository/dao"
	"learning_go/webook/interactive/service"
	"time"
)

// Injectors from wire.go:

func InitGRPCService() *grpc.InteractiveServiceServer {
	duration := _wireDurationValue
	db := ioc.InitDB()
	interactiveDao := dao.NewGORMInteractiveDao(db)
	cmdable := ioc.InitRedis()
	interactiveCache := cache.NewRedisInteractiveCache(cmdable)
	interactiveRepository := repository.NewCachedInteractiveRepository(duration, interactiveDao, interactiveCache)
	interactiveService := service.NewInteractiveServiceI(interactiveRepository)
	interactiveServiceServer := grpc.NewInteractiveServiceServer(interactiveService)
	return interactiveServiceServer
}

var (
	_wireDurationValue = time.Minute
)

// wire.go:

var (
	thirdProvider          = wire.NewSet(ioc.InitDB, ioc.InitRedis)
	interactiveSvcProvider = wire.NewSet(wire.Value(time.Minute), dao.NewGORMInteractiveDao, cache.NewRedisInteractiveCache, repository.NewCachedInteractiveRepository, service.NewInteractiveServiceI)
)
