// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"learning_go/webook/interactive/events"
	"learning_go/webook/interactive/grpc"
	"learning_go/webook/interactive/ioc"
	"learning_go/webook/interactive/repository"
	"learning_go/webook/interactive/repository/cache"
	"learning_go/webook/interactive/repository/dao"
	"learning_go/webook/interactive/service"
	"time"
)

// Injectors from wire.go:

func InitApp() *App {
	duration := _wireDurationValue
	srcDB := ioc.InitSrcDB()
	dstDB := ioc.InitDstDB()
	doubleWritePool := ioc.InitDoubleWritePool(srcDB, dstDB)
	db := ioc.InitBizDB(doubleWritePool)
	interactiveDao := dao.NewGORMInteractiveDao(db)
	cmdable := ioc.InitRedis()
	interactiveCache := cache.NewRedisInteractiveCache(cmdable)
	interactiveRepository := repository.NewCachedInteractiveRepository(duration, interactiveDao, interactiveCache)
	interactiveService := service.NewInteractiveServiceI(interactiveRepository)
	interactiveServiceServer := grpc.NewInteractiveServiceServer(interactiveService)
	server := ioc.InitGRPCXServer(interactiveServiceServer)
	client := ioc.InitKafka()
	interactiveReadEventBatchConsumer := events.NewInteractiveReadEventBatchConsumer(client, interactiveRepository)
	saramaConsumer := ioc.InitFixerConsumer(client, srcDB, dstDB)
	v := ioc.InitConsumers(interactiveReadEventBatchConsumer, saramaConsumer)
	syncProducer := ioc.InitSyncProducer(client)
	int2 := _wireIntValue
	engine := ioc.InitMigratorScheduler(doubleWritePool, srcDB, dstDB, syncProducer, int2)
	app := &App{
		server:    server,
		consumers: v,
		webServer: engine,
	}
	return app
}

var (
	_wireDurationValue = time.Minute
	_wireIntValue      = 10
)

// wire.go:

var (
	thirdProvider          = wire.NewSet(ioc.InitBizDB, ioc.InitRedis, ioc.InitKafka, ioc.InitDstDB, ioc.InitSrcDB, ioc.InitDoubleWritePool)
	interactiveSvcProvider = wire.NewSet(wire.Value(time.Minute), dao.NewGORMInteractiveDao, cache.NewRedisInteractiveCache, repository.NewCachedInteractiveRepository, service.NewInteractiveServiceI)
	migratorSvcProvider    = wire.NewSet(ioc.InitSyncProducer, ioc.InitMigratorScheduler, wire.Value(10)) //batchsize
)
