// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"learning_go/webook/comment/ioc"
	"learning_go/webook/comment/repository"
	"learning_go/webook/comment/repository/dao"
	"learning_go/webook/comment/service"
)

// Injectors from wire.go:

func InitApp() *App {
	db := ioc.InitDB()
	commentDao := dao.NewGORMCommentDao(db)
	commentRepository := repository.NewCachedCommentRepository(commentDao)
	commentService := service.NewCommentServiceI(commentRepository)
	server := ioc.InitGRPCXServer(commentService)
	app := &App{
		server: server,
	}
	return app
}

// wire.go:

var thirdProvider = wire.NewSet(ioc.InitDB, ioc.InitRedis)
