version: "3.0"
services:
  mysql8:
    image: mysql:8.0.29  # 指定镜像，镜像相当于一个只读的原始文件，容器启动服务会基于镜像创建一个可写层，从而隔离不同服务
    # 容器 = 镜像+可写层+网络/进程环境+启动运行
    restart: always
    command:
      - --default_authentication_plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      #      设置初始化脚本，将本地的./script/mysql/下的文件挂载到容器的/docker-entrypoint-initdb.d/目录下，该目录会在初始化时自动执行.sql脚本
      - ./script/mysql/:/docker-entrypoint-initdb.d/
    ports:
      #      把本机的13316端口映射到容器（虚拟化服务）的3306端口，容器的mysql服务，在本机访问13316，就相当于访问容器的3306端口
      - "13316:3306"
  redis:
    image: 'bitnami/redis:7.2'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
  # 分布式 远程配置中心etcd，可以实现动态管理配置参数
  etcd:
    image: "bitnami/etcd:latest"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes  # 容器的环境变量 允许无认证方式访问 etcd（即不用用户名密码就能连上 etcd）。
    ports:
      - "12379:2379"

  mongo:
    image: mongo:6.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"

  prometheus:
    image: prom/prometheus:v2.47.2
    volumes:
      #      - 将本地的 prometheus 配置文件映射到容器内的配置文件
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      #      - 访问数据的端口
      - 9090:9090
  grafana:
    image: grafana/grafana-enterprise:10.2.0
    ports:
      - 3000:3000

  zipkin:
    #    用的是不支持 Kafka 之类的简化版本
    image: openzipkin/zipkin-slim:2.24
    ports:
      - '9411:9411'

  kafka:
    image: 'bitnami/kafka:3.6.0'
    ports:
      - '9092:9092'
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      #      - 允许自动创建 topic，线上不要开启，创建太多topic会对性能产生影响
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      # EXTERNAL配置docker-compose外连接kafka的端口，PLAINTEXT配置docker-compose内连接kafka的端口
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

#  # 为mongoDB提供一个web界面，用于在浏览器内管理和查看mongoDB
#  mongo-express:
#    image: mongo-express:1.0.2-20-alpine3.19
#    ports:
#      - "18081:8081"
#    restart: always
#    environment:
#      # web界面的用户名
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      # 密码
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
#      # 连接到docker内部的mongoDB服务
#      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
