// Code generated by MockGen. DO NOT EDIT.
// Source: D:/go_project/learning_go/webook/internal/repository/code.go
//
// Generated by this command:
//
//	mockgen -source=D:/go_project/learning_go/webook/internal/repository/code.go -package=repomocks -destination=D:/go_project/learning_go/webook/internal/repository/mocks/code_mock.go
//

// Package repomocks is a generated GoMock package.
package repomocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCodeRepository is a mock of CodeRepository interface.
type MockCodeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCodeRepositoryMockRecorder
	isgomock struct{}
}

// MockCodeRepositoryMockRecorder is the mock recorder for MockCodeRepository.
type MockCodeRepositoryMockRecorder struct {
	mock *MockCodeRepository
}

// NewMockCodeRepository creates a new mock instance.
func NewMockCodeRepository(ctrl *gomock.Controller) *MockCodeRepository {
	mock := &MockCodeRepository{ctrl: ctrl}
	mock.recorder = &MockCodeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCodeRepository) EXPECT() *MockCodeRepositoryMockRecorder {
	return m.recorder
}

// CreateRetry mocks base method.
func (m *MockCodeRepository) CreateRetry(ctx context.Context, biz, phone, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRetry", ctx, biz, phone, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRetry indicates an expected call of CreateRetry.
func (mr *MockCodeRepositoryMockRecorder) CreateRetry(ctx, biz, phone, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRetry", reflect.TypeOf((*MockCodeRepository)(nil).CreateRetry), ctx, biz, phone, code)
}

// DeleteRetry mocks base method.
func (m *MockCodeRepository) DeleteRetry(ctx context.Context, biz, phone string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRetry", ctx, biz, phone)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRetry indicates an expected call of DeleteRetry.
func (mr *MockCodeRepositoryMockRecorder) DeleteRetry(ctx, biz, phone any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRetry", reflect.TypeOf((*MockCodeRepository)(nil).DeleteRetry), ctx, biz, phone)
}

// FindByKey mocks base method.
func (m *MockCodeRepository) FindByKey(ctx context.Context, biz, phone string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByKey", ctx, biz, phone)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByKey indicates an expected call of FindByKey.
func (mr *MockCodeRepositoryMockRecorder) FindByKey(ctx, biz, phone any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByKey", reflect.TypeOf((*MockCodeRepository)(nil).FindByKey), ctx, biz, phone)
}

// Store mocks base method.
func (m *MockCodeRepository) Store(ctx context.Context, biz, phone, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, biz, phone, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockCodeRepositoryMockRecorder) Store(ctx, biz, phone, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockCodeRepository)(nil).Store), ctx, biz, phone, code)
}

// Verify mocks base method.
func (m *MockCodeRepository) Verify(ctx context.Context, biz, phone, inputCode string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", ctx, biz, phone, inputCode)
	ret0, _ := ret[0].(error)
	return ret0
}

// Verify indicates an expected call of Verify.
func (mr *MockCodeRepositoryMockRecorder) Verify(ctx, biz, phone, inputCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockCodeRepository)(nil).Verify), ctx, biz, phone, inputCode)
}
