// Code generated by MockGen. DO NOT EDIT.
// Source: D:/go_project/learning_go/webook/internal/repository/interactive.go
//
// Generated by this command:
//
//	mockgen -source=D:/go_project/learning_go/webook/internal/repository/interactive.go -package=repomocks -destination=D:/go_project/learning_go/webook/internal/repository/mocks/interactive_mocks.go
//

// Package repomocks is a generated GoMock package.
package repomocks

import (
	context "context"
	"learning_go/webook/main/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockInteractiveRepository is a mock of InteractiveRepository interface.
type MockInteractiveRepository struct {
	ctrl     *gomock.Controller
	recorder *MockInteractiveRepositoryMockRecorder
	isgomock struct{}
}

// MockInteractiveRepositoryMockRecorder is the mock recorder for MockInteractiveRepository.
type MockInteractiveRepositoryMockRecorder struct {
	mock *MockInteractiveRepository
}

// NewMockInteractiveRepository creates a new mock instance.
func NewMockInteractiveRepository(ctrl *gomock.Controller) *MockInteractiveRepository {
	mock := &MockInteractiveRepository{ctrl: ctrl}
	mock.recorder = &MockInteractiveRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInteractiveRepository) EXPECT() *MockInteractiveRepositoryMockRecorder {
	return m.recorder
}

// AddCollectItem mocks base method.
func (m *MockInteractiveRepository) AddCollectItem(ctx context.Context, biz string, bizId, cid, uid int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCollectItem", ctx, biz, bizId, cid, uid)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCollectItem indicates an expected call of AddCollectItem.
func (mr *MockInteractiveRepositoryMockRecorder) AddCollectItem(ctx, biz, bizId, cid, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCollectItem", reflect.TypeOf((*MockInteractiveRepository)(nil).AddCollectItem), ctx, biz, bizId, cid, uid)
}

// Collected mocks base method.
func (m *MockInteractiveRepository) Collected(ctx context.Context, biz string, bizId, uid int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Collected", ctx, biz, bizId, uid)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Collected indicates an expected call of Collected.
func (mr *MockInteractiveRepositoryMockRecorder) Collected(ctx, biz, bizId, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Collected", reflect.TypeOf((*MockInteractiveRepository)(nil).Collected), ctx, biz, bizId, uid)
}

// DecreaseLikeCnt mocks base method.
func (m *MockInteractiveRepository) DecreaseLikeCnt(ctx context.Context, biz string, bizId, uid int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecreaseLikeCnt", ctx, biz, bizId, uid)
	ret0, _ := ret[0].(error)
	return ret0
}

// DecreaseLikeCnt indicates an expected call of DecreaseLikeCnt.
func (mr *MockInteractiveRepositoryMockRecorder) DecreaseLikeCnt(ctx, biz, bizId, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecreaseLikeCnt", reflect.TypeOf((*MockInteractiveRepository)(nil).DecreaseLikeCnt), ctx, biz, bizId, uid)
}

// GetByIds mocks base method.
func (m *MockInteractiveRepository) GetByIds(ctx context.Context, ids []int64) (map[int64]domain.Interactive, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIds", ctx, ids)
	ret0, _ := ret[0].(map[int64]domain.Interactive)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIds indicates an expected call of GetByIds.
func (mr *MockInteractiveRepositoryMockRecorder) GetByIds(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIds", reflect.TypeOf((*MockInteractiveRepository)(nil).GetByIds), ctx, ids)
}

// GetLikeTop mocks base method.
func (m *MockInteractiveRepository) GetLikeTop(ctx context.Context, biz string, topNum int64) ([]domain.Interactive, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLikeTop", ctx, biz, topNum)
	ret0, _ := ret[0].([]domain.Interactive)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLikeTop indicates an expected call of GetLikeTop.
func (mr *MockInteractiveRepositoryMockRecorder) GetLikeTop(ctx, biz, topNum any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLikeTop", reflect.TypeOf((*MockInteractiveRepository)(nil).GetLikeTop), ctx, biz, topNum)
}

// GetThree mocks base method.
func (m *MockInteractiveRepository) GetThree(ctx context.Context, biz string, bizId int64) (domain.Interactive, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetThree", ctx, biz, bizId)
	ret0, _ := ret[0].(domain.Interactive)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetThree indicates an expected call of GetThree.
func (mr *MockInteractiveRepositoryMockRecorder) GetThree(ctx, biz, bizId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetThree", reflect.TypeOf((*MockInteractiveRepository)(nil).GetThree), ctx, biz, bizId)
}

// IncreaseLikeCnt mocks base method.
func (m *MockInteractiveRepository) IncreaseLikeCnt(ctx context.Context, biz string, bizId, uid int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncreaseLikeCnt", ctx, biz, bizId, uid)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncreaseLikeCnt indicates an expected call of IncreaseLikeCnt.
func (mr *MockInteractiveRepositoryMockRecorder) IncreaseLikeCnt(ctx, biz, bizId, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncreaseLikeCnt", reflect.TypeOf((*MockInteractiveRepository)(nil).IncreaseLikeCnt), ctx, biz, bizId, uid)
}

// IncreaseReadCount mocks base method.
func (m *MockInteractiveRepository) IncreaseReadCount(ctx context.Context, biz string, bizId int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncreaseReadCount", ctx, biz, bizId)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncreaseReadCount indicates an expected call of IncreaseReadCount.
func (mr *MockInteractiveRepositoryMockRecorder) IncreaseReadCount(ctx, biz, bizId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncreaseReadCount", reflect.TypeOf((*MockInteractiveRepository)(nil).IncreaseReadCount), ctx, biz, bizId)
}

// IncreaseReadCountN mocks base method.
func (m *MockInteractiveRepository) IncreaseReadCountN(ctx context.Context, bizs []string, aids []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncreaseReadCountN", ctx, bizs, aids)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncreaseReadCountN indicates an expected call of IncreaseReadCountN.
func (mr *MockInteractiveRepositoryMockRecorder) IncreaseReadCountN(ctx, bizs, aids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncreaseReadCountN", reflect.TypeOf((*MockInteractiveRepository)(nil).IncreaseReadCountN), ctx, bizs, aids)
}

// Liked mocks base method.
func (m *MockInteractiveRepository) Liked(ctx context.Context, biz string, bizId, uid int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Liked", ctx, biz, bizId, uid)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Liked indicates an expected call of Liked.
func (mr *MockInteractiveRepositoryMockRecorder) Liked(ctx, biz, bizId, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Liked", reflect.TypeOf((*MockInteractiveRepository)(nil).Liked), ctx, biz, bizId, uid)
}
