// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/google/wire"
	"learning_go/webook/interactive/repository"
	"learning_go/webook/interactive/repository/cache"
	"learning_go/webook/interactive/repository/dao"
	"learning_go/webook/interactive/service"
	"time"
)

// Injectors from wire.go:

func InitInteractiveGRPCService() service.InteractiveService {
	duration := _wireDurationValue
	gormDB := InitDB()
	interactiveDao := dao.NewGORMInteractiveDao(gormDB)
	cmdable := InitRedis()
	interactiveCache := cache.NewRedisInteractiveCache(cmdable)
	interactiveRepository := repository.NewCachedInteractiveRepository(duration, interactiveDao, interactiveCache)
	interactiveService := service.NewInteractiveServiceI(interactiveRepository)
	return interactiveService
}

var (
	_wireDurationValue = time.Minute
)

// wire.go:

var thirdProvider = wire.NewSet(InitRedis, InitDB)

var interactiveSvcProvider = wire.NewSet(wire.Value(time.Minute), dao.NewGORMInteractiveDao, cache.NewRedisInteractiveCache, repository.NewCachedInteractiveRepository, service.NewInteractiveServiceI)
