// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"learning_go/webook/user/ioc"
	"learning_go/webook/user/repository"
	"learning_go/webook/user/repository/cache"
	"learning_go/webook/user/repository/dao"
	"learning_go/webook/user/service"
)

// Injectors from wire.go:

func InitApp() *App {
	db := ioc.InitDB()
	userDAO := dao.NewUserDAO(db)
	cmdable := ioc.InitRedis()
	userCache := cache.NewUserCache(cmdable)
	userRepository := repository.NewUserRepository(userDAO, userCache)
	userService := service.NewUserService(userRepository)
	server := ioc.InitGRPCXServer(userService)
	app := &App{
		server: server,
	}
	return app
}

// wire.go:

var thirdProvider = wire.NewSet(ioc.InitDB, ioc.InitRedis)
